function [f1, f2] = task3
%  mean and var of sequence generated by HMM


A=[.99 .01; .03 .97];
p0=[0.75;0.25];
mc=MarkovChain(p0,A);

nPaths = 10000;

pDgen(1)=GaussD('Mean',0,'StDev',1);
pDgen(2)=GaussD('Mean',3,'StDev',2);

hmm = HMM(mc, pDgen);

outPut = hmm.rand(nPaths);

disp (mean(outPut));
disp (var(outPut));

